[pytest]
pythonpath = .
asyncio_mode = auto
testpaths = tests
addopts = --strict-markers
filterwarnings =
    ignore:'pkgutil.find_loader' is deprecated:DeprecationWarning:pytesseract
    ignore:'asyncio.iscoroutinefunction' is deprecated:DeprecationWarning:slowapi
    ignore:builtin type Swig.* has no __module__ attribute:DeprecationWarning
    ignore:Using `httpx` with `starlette.testclient` is deprecated
